default: &default
  adapter: postgresql
  timeout: 5000
  database: oc_development
  pool: 5
  host: db
  port: 5432
  username: postgres
  password: <%= ENV["DB_ENV_POSTGRES_PASSWORD"] %>

development:
  adapter: postgresql
  user: postgres
  password:
  encoding: unicode
  database: db/oc_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: oc_production

